const fieldNames = {
    amt: 'Amount',
    appr: 'Approver',
    ass: 'Assessment from CISO or PPO',
    atfr: 'Accomplished Transfer Form with MR',
    borr: 'Borrowed Items / Equipment',
    company: 'Company',
    done: 'Status',
    etc: 'Others',
    from: 'From',
    gtappr: 'Gate Approver',
    item: 'Item',
    location: 'Location',
    manresa: 'Manresa Farm',
    nature: 'Nature',
    num: 'Number of Items',
    orn: 'Official Receipt Number',
    prop: 'Property Donation',
    ptcs: 'Particulars',
    rcv: 'Receiver',
    receipt_num: 'Receipt Number',
    remarks: 'Remarks',
    repl: 'For Replacement',
    repr: 'For Repair',
    req2borr: 'Request to Borrow Form',
    req: 'Requestor',
    _reqs: 'Required',
    reqs_uploaded: 'Required Attachments Uploaded?',
    return: 'Return',
    sales: 'Sales',
    sign: 'Signature',
    spec: 'Specifications',
    searsolin: 'Southeast Asia Rural Social Leadership Institute',
    tag: 'Tag',
    tfno: 'Transfer Form Number',
    title: 'Title',
    to: 'To',
    trans: 'Transfer Location',
    type: 'Type',
    ver: 'Verifier',
    warranty: 'Warranty',
    xugs: 'XU Grade School',
    xujhs: 'XU Junior High School',
    xuor: 'XU Official Receipt',
    xushs: 'XU Senior High School',
}

module.exports = fieldNames;